### ISSUE TITLE
X750 Geekworm Error sensor not detected at 0x36 

### ISSUE THREAD

**Issue by OPSDZ** [Beduir/x720#1]
hi @Beduir  can u please help me to integrate X750 
i flow ur steps by step sensor https://community.home-assistant.io/t/greekworm-ups-hat/53059/13
but i got  sensor not detected at 0x36 
My config:
Raspberry Pi 4 4Go Hasso 5.10 64bit
ic2 enabled as u mentioned .
![138325048_531532614474380_5934971580329794342_n](https://user-images.githubusercontent.com/17110456/104482685-81d4ec80-55c7-11eb-8a46-14222162b3d1.jpg)

many thanks in advance

**Comment by Beduir** [comment]
Probably the module did not turn on.
1. Format a USB stick with FAT32/EXT4/NTFS and name it CONFIG (in all capitals) (important).

![image](https://user-images.githubusercontent.com/2959300/104538152-e9ce1600-564d-11eb-8755-882fc7d4770d.png)

2. Create the "modules" folder.
3. Create an "rpi-i2c.conf" file in the "modules" folder with the text:
```
i2c-dev
i2c-bcm2708
```
4. Insert the flash drive into the RPI.
5. Reboot HassOS.

Just in case, you should also check that there are lines in config.txt:
```
dtparam=i2c1=on
dtparam=i2c_arm=on
```

The flash drive can be disconnected after a reboot.

X750 works, I'm using it myself right now.

**Comment by OPSDZ** [comment]
Yeeeees it's working now thank you Legend @Beduir
